from pathlib import Path

APP_NAME = "Sueños Dorados"
APP_SUBTITLE = "Gestión Administrativa"
LOGO_PATH = "suenos_dorados.jpeg"

COLOR_PRIMARIO = "#D99A19"
COLOR_PRIMARIO_HOVER = "#B97909"
COLOR_SECUNDARIO = "#344054"
COLOR_SIDEBAR = "#172033"
COLOR_FONDO = "#E9EEF8"
COLOR_BLANCO = "#FFFFFF"
COLOR_BORDE = "#D8DEEA"
COLOR_TEXTO = "#182233"
COLOR_TEXTO_G = "#667085"
COLOR_EXITO = "#1F9D55"
COLOR_ALERTA = "#D92D20"
COLOR_INFO = "#3277F6"

BASE_DIR = Path(__file__).resolve().parent
LOGO_FILE = BASE_DIR / LOGO_PATH
